name: rnaflow
channels:
  - pytorch
  - pyg
  - dglteam/label/cu117
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blast=2.14.1=pl5321h6f7f691_0
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cd-hit=4.8.1=h43eeafb_9
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - cryptography=41.0.3=py310hdda0065_0
  - csblast=2.2.3=h4ac6f70_3
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - curl=8.2.1=hdbd6064_0
  - debugpy=1.8.0=py310hc6cd4ac_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - dgl=1.1.2.cu117=py310_0
  - entrez-direct=16.2=he881be0_1
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.9.0=py310h06a4308_0
  - gawk=5.1.0=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - hhsuite=3.3.0=py310pl5321h068649b_9
  - hmmer=3.3.2=hdbdd923_4
  - idna=3.4=py310h06a4308_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - infernal=1.1.4=pl5321h031d066_4
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipykernel=6.28.0=pyhd33586a_0
  - ipython=8.19.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.2.0=py310h06a4308_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.6.0=py310hff52083_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.7.2.10=0
  - libcurand=10.3.3.141=0
  - libcurl=8.2.1=h251f7ec_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=13.2.0=h807b86a_0
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.52.0=h2d74bed_1
  - libnpp=11.7.4.75=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjpeg=11.8.0.2=0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.2.0=h7e041cc_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libzlib=1.2.13=hd590300_5
  - mafft=7.520=h031d066_2
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - mmseqs2=13.45111=pl5321hf1761c0_2
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncbi-vdb=3.0.0=pl5321h87f3376_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - networkx=3.1=py310h06a4308_0
  - numpy=1.25.2=py310h5f9d8c6_0
  - numpy-base=1.25.2=py310hb5e798b_0
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openssl=3.2.1=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - perl=5.32.1=0_h5eee18b_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321h166bdaf_0
  - perl-compress-raw-zlib=2.202=pl5321h166bdaf_0
  - perl-encode=3.19=pl5321h166bdaf_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-io-compress=2.201=pl5321hdbdd923_2
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_0
  - perl-json-xs=2.34=pl5321h4ac6f70_6
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h031d066_2
  - perl-parent=0.241=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321h166bdaf_0
  - perl-scalar-list-utils=1.63=pl5321h166bdaf_0
  - perl-storable=3.15=pl5321h166bdaf_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.2.1=py310h06a4308_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.7=py310h2372a71_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.3.1=py310_torch_2.0.0_cu117
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pyzmq=25.1.2=py310h795f18f_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_0
  - scikit-learn=1.3.0=py310h1128e8f_0
  - scipy=1.11.1=py310h5f9d8c6_0
  - setuptools=68.0.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - torchtriton=2.0.0=py310
  - tornado=6.3.3=py310h2372a71_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.14.0=pyhd8ed1ab_0
  - typing_extensions=4.7.1=py310h06a4308_0
  - urllib3=1.26.16=py310h06a4308_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - wget=1.21.4=h251f7ec_1
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - pip:
      - absl-py==2.0.0
      - accelerate==0.25.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - biopython==1.82
      - biotite==0.38.0
      - cachetools==5.3.2
      - click==8.1.7
      - configparser==6.0.0
      - contourpy==1.2.0
      - cpdb-protein==0.2.0
      - cycler==0.12.1
      - cython==3.0.8
      - datasets==2.16.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - e3nn==0.3.3
      - egnn-pytorch==0.2.7
      - einops==0.7.0
      - fair-esm==2.0.0
      - fasteners==0.19
      - flatbuffers==23.5.26
      - fonttools==4.47.0
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.26.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - griddataformats==1.0.2
      - grpcio==1.60.0
      - h5py==3.10.0
      - huggingface-hub==0.20.1
      - hydra-core==1.3.2
      - keras==2.15.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - lightning==2.1.3
      - lightning-utilities==0.10.0
      - llvmlite==0.41.1
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - matplotlib==3.8.2
      - mda-xdrlib==0.2.0
      - mdanalysis==2.7.0
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - mmtf-python==1.1.3
      - mrcfile==1.4.3
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.15
      - numba==0.58.1
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opt-einsum==3.3.0
      - opt-einsum-fx==0.1.4
      - pandas==2.1.4
      - pathtools==0.1.2
      - peft==0.7.1
      - pillow==10.1.0
      - promise==2.3
      - protobuf==4.23.4
      - pyarrow==14.0.2
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pynvml==11.0.0
      - python-dotenv==1.0.0
      - pytorch-lightning==2.1.3
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rsa==4.9
      - safetensors==0.4.1
      - se3-transformer-pytorch==0.9.0
      - seaborn==0.13.1
      - sentry-sdk==1.39.1
      - shortuuid==1.0.11
      - shtab==1.6.5
      - smmap==5.0.1
      - subprocess32==3.5.4
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.35.0
      - termcolor==2.4.0
      - tokenizers==0.15.0
      - torchmetrics==1.2.1
      - transformers==4.36.2
      - tyro==0.6.3
      - tzdata==2023.4
      - wandb==0.12.0
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - xxhash==3.4.1
      - yarl==1.9.4
